// Whole-show export (Phase 5): one zip with every graphic of the show as its own SPX
// Starter folder PLUS one aggregated show_controlpanel.html at the root — the show's
// control page, generated from every graphic's fields and state machine. Run each
// graphic's index.html as a browser source and open the show panel in the same browser:
// every card drives its graphic over that graphic's own BroadcastChannel.
//
//   <show>/show_controlpanel.html
//   <show>/<graphic>/index.html + css/ js/ images/ fonts/ + controlpanel.html

import JSZip from 'jszip';
import { slug } from './common';
import { buildStarterInto } from './targets/spxStarter';
import { renderShowControlPanelHtml } from '../control/controlPanelHtml';
import type { Show } from '../model/shows';

export async function buildShowZip(show: Show): Promise<JSZip> {
  const zip = new JSZip();
  const root = zip.folder(slug(show.name))!;
  const used = new Set<string>();
  for (const graphic of show.graphics) {
    // Two graphics can slug identically ("Ticker" / "ticker!") — suffix the collision.
    let name = slug(graphic.name);
    let n = 2;
    while (used.has(name)) name = `${slug(graphic.name)}_${n++}`;
    used.add(name);
    await buildStarterInto(root.folder(name)!, graphic.template);
  }
  root.file('show_controlpanel.html', renderShowControlPanelHtml(show.name, show.graphics.map((g) => g.template)));
  root.file(
    'README.md',
    `# ${show.name} — show package\n\nGenerated by NoaCG Studio.\n\n` +
      `Each folder is one plug-and-play SPX template (rundown order):\n\n` +
      show.graphics.map((g) => `- ${slug(g.name)}/  (${g.type})`).join('\n') +
      `\n\n## Operating the show (show_controlpanel.html)\n` +
      `Run each graphic's index.html as a browser source (OBS, vMix, a browser tab), then open\n` +
      `show_controlpanel.html in another tab of the SAME browser. One card per graphic: fields,\n` +
      `the state machine's buttons, and Play/Stop/Update/Next — each card drives its own\n` +
      `graphic independently over a BroadcastChannel, no server needed.\n\n` +
      `Extract this folder into your SPX/CasparCG templates directory as-is.\n`,
  );
  return zip;
}
