// Lower-third scaffolding. The generic pieces (font resolution, :root contract, reset,
// scale math, zones, document + runtime skeletons) live in templates/shared/base.ts and are
// composed here with the lower-third specifics: the .l3 structure contract, the auto-fit
// pattern, and the L3 animation presets.
//
// Standard structure contract (all variants; presets rely on it):
//   <div class="l3">            root — positioned by zone; opacity:0 until play()
//     [<div class="l3-accent">] optional accent shape
//     <div class="l3-box">      the panel; presets animate this
//       <div class="l3-mask"><span id="f0" class="l3-name">…</span></div>
//       <div class="l3-mask"><span id="f1" class="l3-title">…</span></div>
//     </div>
//   </div>

import type { SpxTemplate } from '../../model/types';
import { definitionScriptBlock } from '../../model/spxDefinition';
import { resolveEasing } from '../../model/easings';
import {
  fieldsFromOptions,
  resolveOptions,
  type ResolvedOptions,
  type TemplateVariant,
  type WizardOptions,
} from '../../model/wizard';
import {
  baseSettings,
  computeMaxTextWidth,
  computeScale,
  documentHtml,
  resetCanvasCss,
  resolveHeadingFont,
  rootVarsCss,
  runtimeJs,
  zoneCssText,
} from '../shared/base';
import { presetById, type PresetConfig } from './animPresets';

// Re-exported so existing imports (Style panel, sweep) keep working.
export { zoneDecls, type ZoneDecl } from '../shared/base';

// ── What a variant author writes ─────────────────────────────────────────────

export interface L3Design {
  /** Inner HTML of the .l3 root (accent + box with masked lines). Use lineMasks(). */
  html: string;
  /** Variant-specific CSS for the box / lines / accent. Use var(--accent) etc. */
  css: string;
  /** Whether the design includes an .l3-accent element (presets animate it if present). */
  hasAccent: boolean;
}

export interface L3Meta {
  name: string;
  description: string;
  /** SPX UI color label, "1".."7". */
  uicolor: string;
}

// ── Small helpers for variant authors ────────────────────────────────────────

/** Class name for the Nth line (line 0 = name, 1 = title, 2 = kicker/extra). */
export function lineClass(index: number): string {
  return ['l3-name', 'l3-title', 'l3-extra'][index] ?? 'l3-extra';
}

/** The mask-wrapped line elements for the resolved options (SPX writes into id="fN"). */
export function lineMasks(o: ResolvedOptions, indent = '      '): string {
  return o.lines
    .map(
      (line, i) =>
        `${indent}<!-- ${line.title} (f${i}) — SPX writes this field's value straight into the element. -->\n` +
        `${indent}<div class="l3-mask"><span id="f${i}" class="${lineClass(i)}">${line.sample}</span></div>`,
    )
    .join('\n');
}

// ── The assembler ────────────────────────────────────────────────────────────

/**
 * Build the complete SpxTemplate from a variant's design + resolved options.
 * Everything generated here follows docs/DESIGN_LANGUAGE.md.
 */
export function assembleLowerThird(meta: L3Meta, design: L3Design, o: ResolvedOptions): SpxTemplate {
  const font = resolveHeadingFont(o); // imported font wins over the bundled set
  const fields = fieldsFromOptions(o);
  const settings = baseSettings(meta, o);
  const scale = computeScale(o);
  const maxTextWidth = computeMaxTextWidth(o.resolution);

  const html = documentHtml({
    title: meta.name,
    definitionBlock: definitionScriptBlock(settings, fields),
    body: `  <!-- ${meta.name}. Hidden until play(); positioned by the .l3 rule in the CSS. -->
  <div class="l3">
${design.html}
  </div>`,
  });

  const css = `/* ${meta.name} — generated by SPX GFX Builder. Edit freely: this file is yours. */

${rootVarsCss(o, font.stack, scale)}

${font.face}

${resetCanvasCss(o.resolution)}

/* ── Root position (anchor zone) ── */
.l3 {
  position: absolute;
${zoneCssText(o.zone, o.nudge, o.resolution)}
  opacity: 0;                      /* hidden until play() runs the entrance */
}

/* ── Auto-fit: the panel hugs its text and wraps instead of overflowing. ── */
.l3-box {
  width: fit-content;              /* the panel hugs the text */
  max-width: ${maxTextWidth}px;              /* never wider than this — text wraps instead */
  will-change: transform, opacity; /* hint the browser: this element animates */
}
.l3-mask {
  overflow: hidden;                /* lines animate in from behind this mask */
}
.l3-mask > span {
  display: inline-block;           /* so the line can move inside its mask */
  overflow-wrap: break-word;       /* break very long unbroken words */
  text-wrap: balance;              /* wrapped rows get even lengths */
}

/* ── Design ── */
${design.css}
`;

  const preset = presetById(o.animation.presetId);
  // 'auto' uses the preset's hand-tuned ease pair; a named easing preset overrides both phases
  // with its direction-correct curves (Out-flavored in, In-flavored out).
  const ease = resolveEasing(o.animation.easing, preset.autoEase);
  const presetCfg: PresetConfig = {
    lineCount: o.lines.length,
    hasAccent: design.hasAccent,
    steps: o.animation.steps && o.lines.length > 1,
    speed: o.animation.speed,
    easeIn: ease.easeIn,
    easeOut: ease.easeOut,
  };

  const js = runtimeJs(meta.name, preset.emit(presetCfg));

  return {
    name: meta.name,
    type: 'lower-third',
    resolution: o.resolution,
    fps: o.fps,
    html,
    css,
    js,
    fields,
    settings,
    assets: [...o.importedImages, ...(o.customFont ? [o.customFont.asset] : [])],
    layers: o.lines.map((line, i) => ({
      id: `f${i}`,
      type: 'text' as const,
      label: line.title,
      fieldId: `f${i}`,
      text: line.sample,
      styles: {},
    })),
  };
}

/**
 * The authoring API for variant modules: metadata + a design builder in, a complete
 * TemplateVariant out (create() resolves defaults → builds the design → assembles).
 */
export function defineVariant(
  spec: Omit<TemplateVariant, 'create'>,
  meta: L3Meta,
  buildDesign: (o: ResolvedOptions) => L3Design,
): TemplateVariant {
  const variant: TemplateVariant = {
    ...spec,
    create(options?: WizardOptions) {
      const o = resolveOptions(variant, options);
      return assembleLowerThird(meta, buildDesign(o), o);
    },
  };
  return variant;
}
