// LiveOS (NetOn.Live) export: the LiveOS HTML5 graphics engine is OGraf-compliant — any
// OGraf v1 Graphic can be imported and played out directly. So this target IS the OGraf
// package (same manifest + graphic.mjs, built by targets/ograf.ts addOgrafPackage), wrapped
// with LiveOS-specific install instructions. One source, one behaviour: if the OGraf export
// works, the LiveOS export works. (LiveOS also has a proprietary templates.json ingest used
// by Loopic's legacy exporter, but that schema is not publicly documented — the open
// OGraf path is the one to bet on. See docs/EXPORT_TARGETS_RESEARCH.md.)

import JSZip from 'jszip';
import type { SpxTemplate } from '../../model/types';
import { slug } from '../common';
import type { ExportTarget } from '../registry';
import { addOgrafPackage } from './ograf';

function liveosReadme(template: SpxTemplate): string {
  const name = slug(template.name);
  const stepCount = Math.max(1, Number(template.settings.steps) || 1);
  return `# ${template.name} — LiveOS graphic (OGraf package)

Generated by NoaCG Studio.

The LiveOS HTML5 graphics engine is OGraf-compliant, so this package is a standard
EBU OGraf v1 Graphic — LiveOS imports and plays it directly.

## Install
1. Unzip — you get one folder: ${name}/.
2. Copy the folder into your LiveOS graphics/templates location (or import it through
   the LiveOS HTML5 graphics module's OGraf import, depending on your setup).
3. LiveOS reads ${name}.ograf.json and lists the graphic with its data fields.

## Data fields
LiveOS builds the operator inputs from the manifest's data schema:
${template.fields.map((f) => `- ${f.field} (${f.ftype}): ${f.title}`).join('\n') || '- (none)'}

## Playout behaviour
- Take/play runs the entrance animation; take out runs the exit.
- Data updates while on air are applied live (updateAction → the template's update()).
${stepCount > 1 ? `- This graphic has ${stepCount} steps: each further play/continue advances one step
  (playAction → the template's next()); past the last step it animates out.
` : ''}
## Files
- ${name}.ograf.json  The OGraf manifest (name, data schema, step count).
- graphic.mjs         The Graphic Web Component wrapping the template runtime.
- lib/gsap.min.js     Bundled GSAP — no internet needed at playout.
${template.assets.length ? '- images/…            Images used by the template.\n' : ''}
Everything is offline and self-contained. The same package also loads in any other
OGraf v1 compatible renderer.
`;
}

export const liveosTarget: ExportTarget = {
  id: 'liveos',
  label: 'LiveOS (NetOn.Live) export',
  description:
    'An OGraf package for the LiveOS HTML5 graphics engine (OGraf-compliant) — fields become LiveOS operator inputs, play/continue/out drive the template.',
  successMessage: '✓ Exported. Import the unzipped folder into LiveOS (see README.md).',
  async build(template) {
    const zip = new JSZip();
    const root = zip.folder(slug(template.name))!;
    await addOgrafPackage(root, template);
    root.file('README.md', liveosReadme(template));
    return zip;
  },
};
